name: Sync to Hugging Face hub 
  on: 
    push: branches: [main] 
    
# to run this workflow manually from the Actions tab 
workflow_dispatch: 

jobs: 
  sync-to-hf: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout Repo 
      uses: actions/checkout@v3 
      - name: Push to Hugging Face Space 
      uses: huggingface/huggingface-action@v1 
      with: 
      repo-token: ${{ secrets.HF_TOKEN }} 
      repo-id: WpiCs553/Part-1
