name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Push to Hugging Face Space
        uses: WpiCs553/Part-1
        with:
          repo-token: ${{ secrets.HF_TOKEN }}
          repo-id: WpiCs553/Part-1
          branch: main
